# Generated by Django 4.2 on 2023-06-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredient',
            new_name='RecipeIngredient',
        ),
    ]
